### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by Zatrex12345** [diamond-rip/Eden-Titles#1]
How to download This plugin ?

**Comment by Declince** [comment]
or still in devlopment?

**Comment by HierarchyMan** [comment]
It's gradle build it
Or I will share the jar in our Eden unofficial server if u want

**Comment by HierarchyMan** [comment]
Update:
i have the jar but it seems unfinished and not working

**Comment by GoodestEnglish** [comment]
It is still under development.

**Comment by Declince** [comment]
> It's gradle build it

ok
