### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden-Titles#2]
i noticed that the config was empty
i tried making config by looking at the code and default values

is it correct?
![image](https://github.com/diamond-rip/Eden-Titles/assets/97939376/2a35797d-9dc9-431a-b7b8-030bf350d57e)

and is the plugin functional?
and why did u not use stringlist for disabled kits? im confused

**Comment by GoodestEnglish** [comment]
This plugin uses a new system, which aim to auto-generate the config. This is to prevent server owners have a missing config field.

The plugin is not functional currently. 

Disabled-kits is a string list. Where did you notice it is not a string list?

**Comment by HierarchyMan** [comment]
Oh ok
I made a mistake about the string list thing

**Comment by HierarchyMan** [comment]
> This plugin uses a new system, which aim to auto-generate the config. This is to prevent server owners have a missing config field.
> 
> The plugin is not functional currently. 
> 
> Disabled-kits is a string list. Where did you notice it is not a string list?

Can the same config systembe used for eden?
So we won't have to update language config and sounds every single update?

**Comment by HierarchyMan** [comment]
> Oh ok
> I made a mistake about the string list thing

**Comment by GoodestEnglish** [comment]
It is coming soon for config.yml. Unfortunately not for language.yml because there's around 1.5k lines in language.yml of it and it requires to change a huge part of the code to make it works.
